line-length = 120

[lint]
# https://docs.astral.sh/ruff/settings/#select
# default for select is ["E4", "E7", "E9", "F"]
# we add D for docstrings, and N for naming conventions
extend-select = ["D", "N"]
ignore = [
    "E501",
    "D100",
    "D101",
    "D102",
    "D103",
    "D104",
    "D105",
    "D106",
    "D205",
    "D401",
    "D406",
    "E731",
    "D400",
    "D407",
    "N802",
    "N815",
]

[lint.pydocstyle]
convention = "numpy"
